# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='pass_answer1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='pass_answer2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='pass_question1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='pass_question2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='Institute',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('\u5973', 'Male'), ('\u7537', 'Female')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='users',
            name='grade',
            field=models.CharField(choices=[('16', '\u5927\u4e00'), ('15', '\u5927\u4e8c'), ('14', '\u5927\u4e09'), ('13', '\u5927\u56db'), ('\u7855\u58eb', '\u7855\u58eb'), ('\u535a\u58eb', '\u535a\u58eb')], default='', max_length=5),
        ),
    ]
